name: mito
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.9.0=py38_0
  - argon2-cffi=20.1.0=py38h7b6447c_1
  - astunparse=1.6.3=py_0
  - attrs=19.3.0=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=openblas
  - bleach=3.1.5=py_0
  - blinker=1.4=py38_0
  - brotlipy=0.7.0=py38h7b6447c_1000
  - bzip2=1.0.8=h516909a_2
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.6.24=0
  - cachetools=4.1.1=py_0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2020.6.20=py38_0
  - cffi=1.14.1=py38h5bae8af_0
  - chardet=3.0.4=py38_1003
  - click=7.1.2=py_0
  - cryptography=2.9.2=py38h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupti=10.1.168=0
  - cycler=0.10.0=py38_0
  - dbus=1.13.16=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_0
  - expat=2.2.9=he6710b0_2
  - ffmpeg=4.3.1=h167e202_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.2=h5ab3b9f_0
  - gast=0.3.3=py_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.65.0=h6f030ca_0
  - gmp=6.2.0=he1b5a44_2
  - gnutls=3.6.13=h79a8f9a_0
  - google-auth=1.20.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - graphite2=1.3.13=he1b5a44_1001
  - grpcio=1.27.2=py38hf8bcb03_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - h5py=2.10.0=py38hd6299e0_1
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=64.2=he1b5a44_1
  - idna=2.10=py_0
  - importlib-metadata=1.7.0=py38_0
  - importlib_metadata=1.7.0=0
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.16.1=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=py_0
  - jasper=1.900.1=h07fcdf6_1006
  - jedi=0.17.0=py38_0
  - jinja2=2.11.2=py_0
  - joblib=0.16.0=py_0
  - jpeg=9d=h516909a_0
  - jsonschema=3.2.0=py38_0
  - jupyter=1.0.0=py38_7
  - jupyter_client=6.1.6=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.3=py38_0
  - keras-base=2.4.3=py_0
  - keras-gpu=2.4.3=0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.2.0=py38hfd86e86_0
  - lame=3.100=h14c3975_1001
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.34=hc38a660_9
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libclang=9.0.1=default_hde54327_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.5.0=hdf63c60_14
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=17_openblas
  - liblapacke=3.8.0=17_openblas
  - libllvm9=9.0.1=he513fc3_1
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libopencv=4.4.0=py38_2
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.12.3=hd408876_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.14=h7b6447c_0
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - lz4-c=1.9.2=he1b5a44_1
  - mahotas=1.4.10=py38hcb8c335_0
  - markdown=3.1.1=py38_0
  - markupsafe=1.1.1=py38h7b6447c_0
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py38h2af1d28_0
  - mistune=0.8.4=py38h7b6447c_1000
  - nbconvert=5.6.1=py38_0
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.4.1=h1bed415_1002
  - notebook=6.1.1=py38_0
  - nspr=4.27=he1b5a44_1
  - nss=3.55=he751ad9_0
  - numpy=1.19.1=py38h8854b6b_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py_0
  - opencv=4.4.0=py38_2
  - openh264=2.1.1=h8b12597_0
  - openssl=1.1.1g=h7b6447c_0
  - opt_einsum=3.1.0=py_0
  - packaging=20.4=py_0
  - pandoc=2.10=0
  - pandocfilters=1.4.2=py38_1
  - parso=0.8.0=py_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=7.2.0=py38hb39fc2d_0
  - pip=20.2.2=py38_0
  - pixman=0.38.0=h516909a_1003
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - protobuf=3.12.3=py38he6710b0_0
  - ptyprocess=0.6.0=py38_0
  - py-opencv=4.4.0=py38h23f93f0_2
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_2
  - pygments=2.6.1=py_0
  - pyjwt=1.7.1=py38_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.12.3=py38ha8c2ead_3
  - pyrsistent=0.16.0=py38h7b6447c_0
  - pysocks=1.7.1=py38_0
  - python=3.8.5=h4d41432_2_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pyyaml=5.3.1=py38h7b6447c_1
  - pyzmq=19.0.1=py38he6710b0_1
  - qt=5.12.5=hd8c4c69_1
  - qtconsole=4.7.5=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.6=py_0
  - scikit-learn=0.23.1=py38h7ea95a0_0
  - scipy=1.5.0=py38habc2bb6_0
  - send2trash=1.5.0=py38_0
  - setuptools=49.2.0=py38_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h62c20be_0
  - tensorboard=2.2.1=pyh532a8cf_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.2.0=gpu_py38hb782248_0
  - tensorflow-base=2.2.0=gpu_py38h83e3d50_0
  - tensorflow-estimator=2.2.0=pyh208ff02_0
  - tensorflow-gpu=2.2.0=h0d30ee6_0
  - termcolor=1.1.0=py38_1
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.0.4=py38h7b6447c_1
  - tqdm=4.48.2=py_0
  - traitlets=4.3.3=py38_0
  - urllib3=1.25.10=py_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - werkzeug=1.0.1=py_0
  - wheel=0.34.2=py38_0
  - widgetsnbextension=3.5.1=py38_0
  - wrapt=1.12.1=py38h7b6447c_1
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.11=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.2=he6710b0_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h6597ccf_2
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
prefix: /home/daniel_haehn/miniconda2/envs/mito

